Repository Cadasta/cadasta-platform, pull requests merged in 2018-03, with the labels that each got.

#2000 Dashboard changes
  cadasta/core/static/css/main.scss
  cadasta/organization/tests/test_views_default_projects.py
  cadasta/organization/views/default.py
  cadasta/templates/organization/project_dashboard_member.html
  requirements/dev.txt
Labels: PR: approved

#2008 Add option to silence DB logs during dev process
  cadasta/config/settings/dev.py
Labels: PR: approved

#2009 Reorganize functional tests into 4 batches; simplify Travis config
  .travis.yml
  requirements/dev.txt
  tox.ini
Labels: PR: needs review

#2007 Make async spatial requests concurrently
  cadasta/core/static/js/map_utils.js
Labels: PR: approved, PR: needs testing, performance

#2006 Improve async locations endpoint response speed
  cadasta/questionnaires/models.py
  cadasta/search/tests/test_views_async.py
  cadasta/spatial/migrations/0011_add_label_field.py
  cadasta/spatial/migrations/0012_populate_label_field.py
  cadasta/spatial/models.py
  cadasta/spatial/tests/test_models.py
  cadasta/spatial/tests/test_views_default.py
Labels: PR: approved, PR: migration, PR: needs testing, performance

#1998 Fix #1461 -- Validate required fields
  cadasta/organization/tests/files/uttaran_test.xlsx
  cadasta/questionnaires/managers.py
  cadasta/questionnaires/tests/files/bad-bad-default-language.xlsx
  cadasta/questionnaires/tests/files/bad-bad-label-language.xlsx
  cadasta/questionnaires/tests/files/bad-no-default-language.xlsx
  cadasta/questionnaires/tests/files/ok-monolingual.xlsx
  cadasta/questionnaires/tests/files/ok-multilingual.xlsx
  cadasta/questionnaires/tests/files/t_questionnaire_missing_relevant.xlsx
  cadasta/questionnaires/tests/files/xls-form-attrs.xlsx
  cadasta/questionnaires/tests/files/xls-form-copy.xlsx
  cadasta/questionnaires/tests/files/xls-form-invalid.xlsx
  cadasta/questionnaires/tests/files/xls-form.xlsx
  cadasta/questionnaires/tests/test_managers.py
  cadasta/questionnaires/tests/test_serializers.py
  cadasta/questionnaires/tests/test_validators.py
  cadasta/questionnaires/validators.py
Labels: PR: approved, PR: bugfix, PR: needs testing

#2010 Resolve #1951 -- Replace Opbeat logging with Sentry
  cadasta/accounts/views/api.py
  cadasta/accounts/views/default.py
  cadasta/config/settings/production.py
  cadasta/core/tests/test_util.py
  cadasta/core/util.py
  cadasta/tasks/celery.py
  provision/aws-deploy.yml
  provision/roles/cadasta/application/tasks/main.yml
  provision/roles/cadasta/install/tasks/main.yml
  provision/roles/cadasta/production/handlers/main.yml
  provision/roles/cadasta/production/tasks/main.yml
  provision/roles/webserver/production/templates/uwsgi.ini
  requirements/common.txt
  requirements/production.txt
Labels: PR: approved

#2011 Add multi-lang support to location header
  cadasta/core/static/js/map_utils.js
  cadasta/core/static/js/xlang.js
  cadasta/templates/spatial/location_detail.html
  cadasta/templates/spatial/location_map.html
  cadasta/templates/spatial/location_wrapper.html
Labels: PR: bugfix, PR: needs review

#2013 Rm opbeat variables from ansible tooling
  provision/roles/cadasta/install/tasks/main.yml
  provision/roles/webserver/production/templates/uwsgi.ini
Labels: PR: approved

#2012 Move handler from cadasta/production to cadasta/application
  provision/roles/cadasta/application/handlers/main.yml
Labels: PR: approved, PR: bugfix

#2015 Translate location label on Project Dashboard
  cadasta/templates/organization/project_dashboard.html
Labels: PR: bugfix, PR: needs review, priority: high

#2018 Upgrade functional tests to v0.7.0
  requirements/dev.txt
Labels: PR: approved

#2016 Ensure git commands are run from correct dir
  cadasta/config/settings/production.py
Labels: PR: approved

#2019 Update changelog (v1.17.0)
  CHANGELOG.md
Labels: PR: needs review

#2021 Ugrade Django to 1.11.11
  requirements/common.txt
Labels: PR: approved, priority: critical

#2022 Upgrade cadasta-test to v0.8.0
  requirements/dev.txt
Labels: PR: approved

#2023 Remove recursive template code
  cadasta/templates/organization/project_attrs_import.html
  cadasta/templates/organization/project_defaults_import.html
  cadasta/templates/organization/project_select_import.html
Labels: PR: approved, PR: bugfix, PR: needs testing, priority: critical

#2025 Update BrowserStack access key
  .travis.yml
Labels: PR: needs review, priority: high, security

#2026 Fix recursive async calls on project dashboard
  cadasta/core/static/js/map_utils.js
Labels: PR: bugfix, PR: needs review, priority: critical

#2024 Suppress OSERROR write error
  provision/roles/webserver/production/templates/uwsgi.ini
Labels: PR: approved

#2028 Hide avatars on project dashboard
  cadasta/templates/organization/project_dashboard_member.html
Labels: PR: needs review

#2029 Use new release of drf-tmp-scoped-token (fixes #2017) [branch ch92]
  CHANGELOG.md
  requirements/common.txt
Labels: PR: approved, PR: bugfix, PR: needs testing
