Repository Cadasta/cadasta-platform, pull requests merged in 2018-02, with the labels that each got.

#1978 Upgrade cadasta-test to 0.4.0
  requirements/dev.txt
Labels: PR: approved

#1981 Fixes #1761 -- Bump django-buckets
  requirements/common.txt
Labels: PR: approved, PR: bugfix

#1986 Update cadasta-test to v0.5.0
  requirements/dev.txt
Labels: PR: needs review

#1977 Fixes #1944 -- Prevents demo user from updating profile information
  cadasta/accounts/forms.py
  cadasta/accounts/migrations/0011_change_pw__to__update_profile.py
  cadasta/accounts/models.py
  cadasta/accounts/serializers.py
  cadasta/accounts/tests/test_forms.py
  cadasta/accounts/tests/test_serializers.py
  requirements/dev.txt
Labels: PR: bugfix, PR: needs review

#1988 Update toggling of fields based on party type selection in party forms
  cadasta/core/static/js/party_attrs.js
  cadasta/templates/party/party_add.html
Labels: PR: bugfix

#1987 Improve handling of ValidationErrors for API
  cadasta/core/serializers.py
  cadasta/core/tests/test_views_api.py
  cadasta/core/views/api.py
  cadasta/party/tests/test_serializers.py
  cadasta/questionnaires/tests/test_attr_schemas.py
  cadasta/spatial/tests/test_serializers.py
  cadasta/xforms/mixins/model_helper.py
  cadasta/xforms/tests/test_model_helper.py
  cadasta/xforms/tests/test_views_api.py
  requirements/common.txt
Labels: PR: needs review

#1980 Added glyphicons font
  cadasta/core/static/fonts/bootstrap
Labels: PR: bugfix, PR: needs review

#1984 Test newest jsonattrs lib
  cadasta/party/tests/test_models.py
  requirements/common.txt
Labels: PR: approved, PR: bugfix, PR: needs testing

#1994 Update CHANGELOG.md
  CHANGELOG.md
Labels: PR: approved

#1996 Clear table offset when searching (fixes #1995)
  cadasta/core/static/jsx/paginated-table.jsx
Labels: PR: approved, PR: bugfix, PR: needs testing

#1993 Lower deflate tolerance for project maps
  cadasta/core/static/js/map_utils.js
Labels: PR: approved

#1985 Library for international codes
  cadasta/core/static/css/main.scss
  cadasta/core/static/js/parsleyAddValidator.js
  cadasta/core/static/libphonenumber-js/1.0.24/libphonenumber-js.min.js
  cadasta/core/static/libphonenumber-js/1.0.24/libphonenumber-js.min.js.map
  cadasta/templates/accounts/profile.html
  cadasta/templates/accounts/resend_token_page.html
  cadasta/templates/allauth/account/password_change.html
  cadasta/templates/allauth/account/password_reset.html
  cadasta/templates/allauth/account/password_reset_from_key.html
  cadasta/templates/allauth/account/signup.html
  requirements/dev.txt
Labels: PR: approved, PR: bugfix

#2003 Pushing new messages into transifex
  cadasta/config/locale/en/LC_MESSAGES/django.po
  cadasta/config/locale/en/LC_MESSAGES/djangojs.po
Labels: PR: approved
